import "./globals.css";
import { Rubik, Cinzel, Noto_Serif_JP } from "next/font/google";

const rubik = Rubik({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-rubik",
});

const cinzel = Cinzel({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-cinzel",
});

const serifjp = Noto_Serif_JP({
  subsets: ["latin"],
  display: "swap",
  weight: ["500"],
  variable: "--font-jp",
});

export const metadata = {
  title: "Japansese Art",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} ${cinzel.variable} ${serifjp.variable} font-rubik`}
      >
        {children}
      </body>
    </html>
  );
}
